kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 18.183.193.9
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
- role: worker
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 30082
    hostPort: 30082
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker