registry:
  restart: always
  image: registry:2
  ports:
    - 443:443
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/example.com.crt
    REGISTRY_HTTP_TLS_KEY: /certs/example.com.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_HTTP_ADDR: 0.0.0.0:443
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ./registry-data/data:/var/lib/registry
    - ./registry-data/certs:/certs
    - ./registry-data/auth:/auth